# Generated by Django 3.2.5 on 2021-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211018_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content2',
            field=models.IntegerField(default=100, verbose_name='bal'),
        ),
    ]
