# Generated by Django 3.2.5 on 2021-10-23 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
